### PR TITLE
Refactor and new features according to SDK Reference

### PR DESCRIPTION
**Pull request by tylerlong**
Major changes:

1. Add support for 3-legged authorization
1. Response ==> ApiResponse
1. Add a test project which tests against real server instead of mock
1. Add constants for production and sandbox server urls
1. Refactor code, rename namepace and some variables

@kirill-konshin @grokify @LingForCC  Please kindly review and let me know the issues.

### CODE REVIEW

**Comment by tylerlong** [comment]
I am investigating the `AppVeyor build failed` issue

**Comment by LingForCC** [comment]
Seems fine to me. :+1:

**Comment by grokify** [comment]
I tried this on Xamarin Studio Community 5.10.3 (build 51) building a .NET Console Project Solution and could not get subscription events. Authorization and sending SMS worked fine. I have not tried Xamarin.Android or Xamarin.iOS yet but all three worked previously and should pass regression.

A similar appearing issue had appeared with [Release 0.1.2-alpha6](http://www.nuget.org/packages/RingCentralSDK/0.1.2-alpha6).

I used the following code:

```csharp
using System;

using RingCentral;
using RingCentral.Http;

namespace consoletest
{
	class MainClass
	{
		public static void Action(object message) {
			Console.WriteLine (message.ToString ());
		}
			
		public static void Main (string[] args)
		{
                        var appKey = "myAppKey";
                        var appSecret = "myAppSecret";
                        var serverUrl = "https://platform.devtest.ringcentral.com";
                        var username = "12223334444";
                        var extension = "101";
                        var password = "myPassword";

			var sdk = new SDK(appKey, appSecret, serverUrl, "appName", "appVersion");
			ApiResponse response = sdk.Platform.Authorize(username, extension, password, true);

			String jsonSmsString = "{\"from\":{\"phoneNumber\":\"12223334444\"},\"to\":[{\"phoneNumber\":\"+12223335555\"}],\"text\":\"Hello World\"}";
			Request request = new Request("/restapi/v1.0/account/~/extension/~/sms", jsonSmsString);
			ApiResponse response2 = sdk.Platform.Post(request);

			var subscription = new RingCentral.Subscription.SubscriptionServiceImplementation(){ _platform = sdk.Platform};
			subscription.AddEvent("/restapi/v1.0/account/~/extension/~/presence");
			subscription.AddEvent("/restapi/v1.0/account/~/extension/~/message-store");
			ApiResponse response3 = subscription.Subscribe(Action,Action,Action);

			var wait = Console.ReadLine ();

			Console.WriteLine ("DONE!");
		}
	}
}
```

**Comment by tylerlong** [comment]
I didn't change the pubnub code at all (except some simple renaming) so this is weird. I will take a look later.

**Comment by grokify** [comment]
The previous test was run with the DLL. I ran some new tests with a locally compiled and loaded Nuget package. With Nuget package, REST & Subscription are working similar to `0.1.21`:

1. Xamarin.Mac SMS and subscription are working
1. Xamarin.Android SMS and subscription are working
1. Xamarin.iOS SMS is working but subscription is encountering the issue above

The issue with iOS and subscription does not exist in `0.1.1` but exists in `0.1.21` so this PR is good but we have an issue to investigate which I'll open.

**Pull request merged**
